AWSTemplateFormatVersion: '2010-09-09'
Description: 'TP AWS Lambda - Code chargé depuis src/main.py'

Parameters:
  Environment:
    Type: String
    Description: 'Nom de l’environnement (e.g. votre identifiant sans le learnaws)'
    Default: 'kadeoul'
  BucketName:
    Type: String
    Description: 'Nom du bucket S3 (e.g. votre identifiant sans le learnaws + -bucket)'
    Default: 's3-bucket-trigger-lambda'

Resources:
  # Rôle IAM pour la fonction Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole 
      Policies:
        - PolicyName: !Sub '${Environment}-LambdaS3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Bloquer accès au bucket pour éviter boucle infinie
              - Effect: Deny
                Action: 
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${Environment}-${BucketName}/*'

              # Autoriser accès à DynamoDB
              - Effect: Allow
                Action: 
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource: 'arn:aws:dynamodb:*:*:table/s3-trigger-db'

  # Fonction Lambda
  LambdaTrigger:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Environment}-lambda-trigger'
      Handler: main.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Code: ../infrastructure/src
      Environment:
        Variables:
          DYNAMODB_TABLE: s3-trigger-db

  # Permission pour que S3 invoque la Lambda
  LambdaPermissionForS3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaTrigger
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${Environment}-${BucketName}'

  # Bucket S3 avec notification vers Lambda
  S3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: LambdaPermissionForS3
    Properties:
      BucketName: !Sub '${Environment}-${BucketName}'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt LambdaTrigger.Arn