AWSTemplateFormatVersion: '2010-09-09'
Description: 'TP AWS Lambda - Finalisation avec Table Unique et Filtre Image'

Parameters:
  Environment:
    Type: String
    Description: 'Votre identifiant (ex: kadeoul)'
    Default: 'kadeoul'
  BucketName:
    Type: String
    Description: 'Suffixe du bucket S3'
    Default: 's3-bucket-trigger-lambda'

Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-s3-trigger-db'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole 
      Policies:
        - PolicyName: !Sub '${Environment}-LambdaAccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Autorise la Lambda à lire et écrire UNIQUEMENT dans TA table
              - Effect: Allow
                Action: 
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource: !GetAtt MyDynamoDBTable.Arn

  LambdaTrigger:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Environment}-lambda-trigger'
      Handler: main.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Code: src/
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref MyDynamoDBTable
          AWS_REGION_NAME: !Ref AWS::Region

  LambdaPermissionForS3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaTrigger
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${Environment}-${BucketName}'

  S3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: LambdaPermissionForS3
    Properties:
      BucketName: !Sub '${Environment}-${BucketName}'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt LambdaTrigger.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jpg 