AWSTemplateFormatVersion: '2010-09-09'
Description: 'TP AWS Lambda - Filtrage images et gestion doublons DynamoDB'

Parameters:
  Environment:
    Type: String
    Description: 'Nom de l’environnement'
    Default: 'kadeoul'
  BucketName:
    Type: String
    Description: 'Nom du bucket S3'
    Default: 's3-bucket-trigger-lambda'

Resources:
  # Rôle IAM pour la fonction Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole 
      Policies:
        - PolicyName: !Sub '${Environment}-LambdaS3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Accès à DynamoDB (Lecture pour vérifier l'existence + Écriture)
              - Effect: Allow
                Action: 
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/s3-trigger-db'
              
              # Accès S3 (Limité pour éviter les boucles, mais nécessaire pour la lecture d'infos si besoin)
              - Effect: Allow
                Action:
                  - s3:GetBucketNotification
                Resource: !Sub 'arn:aws:s3:::${Environment}-${BucketName}'

  # Fonction Lambda
  LambdaTrigger:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Environment}-lambda-trigger'
      Handler: main.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Code: src/
      Environment:
        Variables:
          DYNAMODB_TABLE: 's3-trigger-db'
          AWS_REGION_NAME: !Ref AWS::Region

  # Permission pour que S3 invoque la Lambda
  LambdaPermissionForS3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaTrigger
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${Environment}-${BucketName}'

  # Bucket S3 avec FILTRE pour les images
  S3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: LambdaPermissionForS3
    Properties:
      BucketName: !Sub '${Environment}-${BucketName}'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt LambdaTrigger.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jpg # Filtre pour accepter uniquement les .jpg